import { Router } from 'express';
import { authController } from '../controllers/auth.controller';
import { authenticate } from '../middleware/auth';
import { registerValidation, loginValidation, forgotPasswordValidation, resetPasswordValidation, twoFactorValidation } from '../validators/auth';
import { validate } from '../middleware/validate';
import { authLimiter } from '../middleware/rateLimiter';
const router = Router();
router.post('/anon-login', authController.anonLogin.bind(authController));
router.post('/register', authLimiter, registerValidation, validate, authController.register.bind(authController));
router.post('/login', authLimiter, loginValidation, validate, authController.login.bind(authController));
router.post('/refresh-token', authController.refreshToken.bind(authController));
router.post('/logout', authController.logout.bind(authController));
router.post('/forgot-password', authLimiter, forgotPasswordValidation, validate, authController.forgotPassword.bind(authController));
router.post('/reset-password', authLimiter, resetPasswordValidation, validate, authController.resetPassword.bind(authController));
router.get('/verify-email', authController.verifyEmail.bind(authController));
router.post('/2fa/setup', authenticate, authController.setupTwoFactor.bind(authController));
router.post('/2fa/verify', authenticate, twoFactorValidation, validate, authController.verifyTwoFactor.bind(authController));
router.post('/2fa/disable', authenticate, authController.disableTwoFactor.bind(authController));
router.get('/me', authenticate, authController.getMe.bind(authController));
router.post('/set-password', authenticate, authController.setPassword.bind(authController));
router.post('/change-password', authenticate, authController.changePassword.bind(authController));
export default router;
