import { Router } from 'express';
import { feedController } from '../controllers/feed.controller';
import { authenticate, optionalAuth } from '../middleware/auth';
const router = Router();
router.get('/', optionalAuth, feedController.getFeed.bind(feedController));
router.get('/following', authenticate, feedController.getFollowing.bind(feedController));
router.get('/followers', authenticate, feedController.getFollowers.bind(feedController));
router.post('/follow/:userId', authenticate, feedController.follow.bind(feedController));
router.post('/unfollow/:userId', authenticate, feedController.unfollow.bind(feedController));
export default router;
