import { Router } from 'express';
import { postController } from '../controllers/post.controller';
import { authenticate } from '../middleware/auth';
const router = Router();
router.get('/trending', authenticate, postController.getTrending);
router.get('/', authenticate, postController.list);
router.get('/:id', authenticate, postController.getById);
router.post('/', authenticate, postController.create);
router.delete('/:id', authenticate, postController.delete);
router.post('/:id/like', authenticate, postController.like);
router.get('/:id/comments', authenticate, postController.getComments);
router.post('/:id/comment', authenticate, postController.comment);
export default router;
