import { Router } from 'express';
import { teamController } from '../controllers/team.controller';
import { authenticate } from '../middleware/auth';
const router = Router();
router.get('/', authenticate, teamController.list);
router.get('/:id', authenticate, teamController.getById);
router.post('/', authenticate, teamController.create);
router.put('/:id', authenticate, teamController.update);
router.post('/:id/invite', authenticate, teamController.invite);
router.post('/:id/accept-invite', authenticate, teamController.acceptInvite);
router.post('/:id/apply', authenticate, teamController.apply);
router.post('/:id/kick', authenticate, teamController.kick);
export default router;
