import { Response, NextFunction } from 'express';
import { AuthRequest } from '../types';
import prisma from '../config/database';
export class AdminController {
  async getDashboardStats(req: AuthRequest, res: Response, next: NextFunction) { try { const [users, tournaments, jobs, orgs, reports, posts] = await Promise.all([prisma.user.count(), prisma.tournament.count(), prisma.job.count(), prisma.organization.count(), prisma.report.count({ where: { status: 'PENDING' } }), prisma.post.count()]); res.json({ success: true, data: { users, tournaments, jobs, orgs, pendingReports: reports, posts } }); } catch (error) { next(error); } }
  async getUsers(req: AuthRequest, res: Response, next: NextFunction) { try { const { page = '1', limit = '20' } = req.query; const skip = (parseInt(page as string) - 1) * parseInt(limit as string); const [users, total] = await Promise.all([prisma.user.findMany({ skip, take: parseInt(limit as string), include: { profile: true }, orderBy: { createdAt: 'desc' } }), prisma.user.count()]); res.json({ success: true, data: users, meta: { page: parseInt(page as string), limit: parseInt(limit as string), total, totalPages: Math.ceil(total / parseInt(limit as string)) } }); } catch (error) { next(error); } }
  async banUser(req: AuthRequest, res: Response, next: NextFunction) { try { const { reason } = req.body; await prisma.user.update({ where: { id: req.params.id }, data: { banned: true, banReason: reason } }); res.json({ success: true, message: 'User banned' }); } catch (error) { next(error); } }
  async unbanUser(req: AuthRequest, res: Response, next: NextFunction) { try { await prisma.user.update({ where: { id: req.params.id }, data: { banned: false, banReason: null } }); res.json({ success: true, message: 'User unbanned' }); } catch (error) { next(error); } }
  async getReports(req: AuthRequest, res: Response, next: NextFunction) { try { const { page = '1', limit = '20' } = req.query; const skip = (parseInt(page as string) - 1) * parseInt(limit as string); const [reports, total] = await Promise.all([prisma.report.findMany({ skip, take: parseInt(limit as string), include: { reporter: { select: { id: true, email: true, profile: true } }, reported: { select: { id: true, email: true, profile: true } } }, orderBy: { createdAt: 'desc' } }), prisma.report.count()]); res.json({ success: true, data: reports, meta: { page: parseInt(page as string), limit: parseInt(limit as string), total, totalPages: Math.ceil(total / parseInt(limit as string)) } }); } catch (error) { next(error); } }
  async resolveReport(req: AuthRequest, res: Response, next: NextFunction) { try { const { resolution } = req.body; await prisma.report.update({ where: { id: req.params.id }, data: { status: 'RESOLVED', resolution, resolvedAt: new Date() } }); res.json({ success: true, message: 'Report resolved' }); } catch (error) { next(error); } }
  async getAuditLogs(req: AuthRequest, res: Response, next: NextFunction) { try { const { page = '1', limit = '50' } = req.query; const skip = (parseInt(page as string) - 1) * parseInt(limit as string); const [logs, total] = await Promise.all([prisma.auditLog.findMany({ skip, take: parseInt(limit as string), include: { user: { select: { id: true, email: true } } }, orderBy: { createdAt: 'desc' } }), prisma.auditLog.count()]); res.json({ success: true, data: logs, meta: { page: parseInt(page as string), limit: parseInt(limit as string), total, totalPages: Math.ceil(total / parseInt(limit as string)) } }); } catch (error) { next(error); } }
}
export const adminController = new AdminController();
