import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: ['class'],
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    container: { center: true, padding: '1rem', screens: { '2xl': '1400px' } },
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: { DEFAULT: 'hsl(var(--primary))', foreground: 'hsl(var(--primary-foreground))' },
        secondary: { DEFAULT: 'hsl(var(--secondary))', foreground: 'hsl(var(--secondary-foreground))' },
        destructive: { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
        success: { DEFAULT: 'hsl(var(--success))', foreground: 'hsl(var(--success-foreground))' },
        warning: { DEFAULT: 'hsl(var(--warning))', foreground: 'hsl(var(--warning-foreground))' },
        muted: { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
        accent: { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))' },
        popover: { DEFAULT: 'hsl(var(--popover))', foreground: 'hsl(var(--popover-foreground))' },
        card: { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
        neon: {
          cyan: 'hsl(var(--neon-cyan))',
          pink: 'hsl(var(--neon-pink))',
          purple: 'hsl(var(--neon-purple))',
          green: 'hsl(var(--neon-green))',
          yellow: 'hsl(var(--neon-yellow))',
          blue: 'hsl(var(--neon-blue))',
        },
        gaming: {
          purple: '#8B5CF6',
          pink: '#EC4899',
          blue: '#3B82F6',
          cyan: '#06B6D4',
          green: '#22C55E',
          yellow: '#EAB308',
          orange: '#F97316',
          red: '#EF4444',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        xl: 'calc(var(--radius) + 4px)',
        '2xl': 'calc(var(--radius) + 8px)',
      },
      fontFamily: {
        heading: ['Orbitron', 'var(--font-orbitron)', 'system-ui', 'sans-serif'],
        body: ['Inter', 'var(--font-inter)', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      keyframes: {
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up': { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
        'float': { '0%, 100%': { transform: 'translateY(0px)' }, '50%': { transform: 'translateY(-8px)' } },
        'float-slow': { '0%, 100%': { transform: 'translateY(0px)' }, '50%': { transform: 'translateY(-15px)' } },
        'shimmer': { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        'glow-pulse': { '0%, 100%': { boxShadow: '0 0 10px hsl(var(--primary)/0.3)' }, '50%': { boxShadow: '0 0 20px hsl(var(--primary)/0.6), 0 0 40px hsl(var(--primary)/0.2)' } },
        'scale-in': { from: { transform: 'scale(0.95)', opacity: '0' }, to: { transform: 'scale(1)', opacity: '1' } },
        'slide-up': { from: { transform: 'translateY(10px)', opacity: '0' }, to: { transform: 'translateY(0)', opacity: '1' } },
        'slide-down': { from: { transform: 'translateY(-10px)', opacity: '0' }, to: { transform: 'translateY(0)', opacity: '1' } },
        'fade-in': { from: { opacity: '0' }, to: { opacity: '1' } },
        'ping-slow': { '75%, 100%': { transform: 'scale(1.5)', opacity: '0' } },
        'rainbow-border': { '0%': { borderColor: 'hsl(var(--neon-cyan))' }, '25%': { borderColor: 'hsl(var(--neon-pink))' }, '50%': { borderColor: 'hsl(var(--neon-purple))' }, '75%': { borderColor: 'hsl(var(--neon-blue))' }, '100%': { borderColor: 'hsl(var(--neon-cyan))' } },
        'heartbeat': { '0%': { transform: 'scale(1)' }, '50%': { transform: 'scale(1.3)' }, '100%': { transform: 'scale(1)' } },
        'typing-dot': { '0%, 60%, 100%': { transform: 'translateY(0)', opacity: '0.4' }, '30%': { transform: 'translateY(-4px)', opacity: '1' } },
        'sparkle': { '0%': { transform: 'scale(0) rotate(0deg)', opacity: '0' }, '50%': { transform: 'scale(1) rotate(180deg)', opacity: '1' }, '100%': { transform: 'scale(0) rotate(360deg)', opacity: '0' } },
        'overlay-show': { from: { opacity: '0' }, to: { opacity: '1' } },
        'content-show': { from: { opacity: '0', transform: 'translateY(10px) scale(0.98)' }, to: { opacity: '1', transform: 'translateY(0) scale(1)' } },
      },
      animation: {
        'accordion-down': 'accordion-down 0.15s ease-out',
        'accordion-up': 'accordion-up 0.15s ease-out',
        'float': 'float 4s ease-in-out infinite',
        'float-slow': 'float-slow 7s ease-in-out infinite',
        'shimmer': 'shimmer 1.5s linear infinite',
        'glow-pulse': 'glow-pulse 1.5s ease-in-out infinite',
        'scale-in': 'scale-in 0.12s ease-out',
        'slide-up': 'slide-up 0.15s ease-out',
        'slide-down': 'slide-down 0.15s ease-out',
        'fade-in': 'fade-in 0.12s ease-out',
        'ping-fast': 'ping-slow 1.5s cubic-bezier(0, 0, 0.2, 1) infinite',
        'rainbow-border': 'rainbow-border 2.5s linear infinite',
        'heartbeat': 'heartbeat 0.3s ease-in-out',
        'typing-dot': 'typing-dot 1s ease-in-out infinite',
        'sparkle': 'sparkle 1s ease-in-out infinite',
        'overlay-show': 'overlay-show 0.12s ease-out',
        'content-show': 'content-show 0.12s ease-out',
      },
      maxWidth: {
        'linkedin': '1128px',
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
export default config;
